---
title: "1033 Watch"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
    orientation: rows
    source_code: "https://github.com/gavinrozzi/1033-watch"
    vertical_layout: fill
runtime: shiny

---
```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)
library(formattable)
library(DT)
library(lubridate)
library(xts)
library(dygraphs)

# Read in 1033 program data
data1033 <- read_csv('data/data.csv') %>% select(-X1)

# Get state names
state_data <- data.frame(state.name, state.abb)

# Calculate which states received the most shipments
state_summaries <- data1033 %>% group_by(State) %>% tally() %>% arrange(desc(n))

# Get top shipped items
top_items <- data1033 %>% group_by(`Item Name`) %>% tally() %>% arrange(desc(n))

# Parse shipping dates
data1033$`Ship Date` <- as.Date(data1033$`Ship Date`)

# Count shipments by day

count_by_date <- data1033 %>% group_by(`Ship Date`) %>% tally()

# Create time series object

count_ts <- as.xts(ts(start = min(count_by_date$`Ship Date`), end = max(count_by_date$`Ship Date`), data = count_by_date$n))


```

National Stats
=====================================

About Your State {.sidebar}
-----------------------------------------------------------------------
The [1033 program](https://www.dla.mil/DispositionServices/Offers/Reutilization/LawEnforcement/ProgramFAQs.aspx) is an initiative that allows the Department of Defense to provide excess military equipment to state & local law enforcement agencies.

This dashboard is tracking how much each state has received under the program, and what type of equipment they received.

Created by [Gavin Rozzi](https://www.gavinrozzi.com/)

Row
-----------------------------------------------------------------------

### Total shipments

```{r}
renderValueBox({
  total_shipments <- prettyNum(nrow(data1033),big.mark=",")
  valueBox(total_shipments , 
           icon = "fa-truck")
})
```

### Value of equipment received

```{r}
renderValueBox({
  total_value <- currency(sum(data1033$`Acquisition Value`))
  valueBox(total_value , 
           icon = "fa-money-bill-wave")
})
```


### Agencies received equipment

```{r}
renderValueBox({
  department_count <- prettyNum(nrow(distinct(data1033, `Station Name (LEA)`)),big.mark=",")
  valueBox(department_count , 
           icon = "fa-balance-scale")
})
```

Row {data-width=650}
-----------------------------------------------------------------------

### National Shipments

```{r}
fig <- plot_geo(state_summaries, locationmode = 'USA-states') 
fig <- fig %>% add_trace(
  locations = ~State,
  z = ~n,
  colors='viridis')

fig <- fig %>%  
layout(geo = list(scope = 'usa'))
fig <- fig %>% colorbar(title = "Total shipments received")
fig
```

Row {data-width=450}
-----------------------------------------------------------------------

### Top Items Received By States

```{r}
top5 <- top_items %>% top_n(5)

top5$`Item Name` <- factor(top5$`Item Name`, levels = top5$`Item Name`)
fig <- plot_ly(
  x = top5$`Item Name`,
  y = top5$n,
  type = "bar"
)
fig

```

### Shipments By Date

```{r}

renderDygraph(dygraph(count_ts)%>% 
  dyRangeSelector())
```


Lookup Your State
=====================================

About Your State {.sidebar}
-----------------------------------------------------------------------

Select your state below. Search your town's police department using the search box.

```{r}
selectInput("state", "State:", choices = distinct(data1033, `State`))
```


Row
-----------------------------------------------------------------------

### Total shipments

```{r}
renderValueBox({
  total_shipments <- nrow(data1033 %>% filter(State == input$state))
  valueBox(total_shipments , 
           icon = "fa-truck")
})
```

### Value of equipment received

```{r}
renderValueBox({
  state_equipment <- data1033 %>% filter(State == input$state)
  state_value <- currency(sum(state_equipment$`Acquisition Value`))
  valueBox(state_value , 
           icon = "fa-money-bill-wave")
})
```


### Agencies received equipment

```{r}
renderValueBox({
  state_equipment <- data1033 %>% filter(State == input$state)
  department_count <- nrow(distinct(state_equipment, `Station Name (LEA)`))
  valueBox(department_count , 
           icon = "fa-balance-scale")
})
```

Row
-----------------------------------------------------------------------

```{r}
DT::renderDataTable({
  DT::datatable(data1033 %>% filter(State == input$state) %>% arrange(desc(`Ship Date`)) %>% select(-State, -`Station Type`), extensions = 'Responsive', escape = FALSE, rownames = FALSE,
  options = list(
    bPaginate = TRUE
  ))
})
```